### ISSUE TITLE
Proposal : Include Date Range Picker

### ISSUE THREAD

**Issue by tzsk** [vue-bulma/datepicker#13]
The DatePicker looks so awesome. But it lacks a few things. Maybe if it is identical in functionality with jQuery DatePicker it would have been huge difference. Like start and End date. And hooks to every bit of data. Methods and Events.

For now my proposal is to include Date Range Picker. It would be a nice inclusion.

**Comment by hwupu** [comment]
Actually it is documented in https://chmln.github.io/flatpickr/#options

My solution is: 
```
config = {
  mode: 'range',
  defaultDate: '2016-12-12 to 2016-12-13',  // or you can make it dynamic; I simply pass new Date().toISOString()
}
```
