### ISSUE TITLE
How do I programmatically control the datepicker? 

### ISSUE THREAD

**Issue by hwupu** [vue-bulma/datepicker#14]
As referred in API section, https://chmln.github.io/flatpickr/, I will like to programmatically control it. For instance, when user want to reset/clear form, I'll like to set datetime picker to its default value. I should be able to do so by using `setDate()`, but how do I talk to the instance at the first hand?

**Comment by beliolfa** [comment]
+1

**Comment by PsychicCat** [comment]
to control the value just manipulate the `:value` prop

**Comment by luventa** [comment]
yes I understood that `v-model` on component element needs a `value` prop. But it's not requisite.
This issue has been fixed in [4dce70f](https://github.com/vue-bulma/datepicker/commit/4dce70f7e44ab24315d803ffa9f38f542c3a57af)

Now we can merely bind data to datepicker like this:

```vue
<datepicker v-model="value"></datepicker>
```

**Comment by zywyz** [comment]
Does it work correctly now?

I have `<datepicker v-model="startDate"></datepicker>`
When I pick date everything is ok - startDate updates, but when I programatically clear `startDate = ''` it doesn't clear in datepicker input.
Any ideas?

**Comment by Rossidges** [comment]
Hi, know this is a bit old.
If anyone else is struggling with this... i found the following works using refs:

```<datepicker v-model="date" ref="fp"></datepicker>```
to clear input
```this.$refs.fp.datepicker.clear()```
