### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by vniko** [vue-bulma/datepicker#20]
Hi, just tried  to use this component and it crashes to blank page
Vue v2.1.10
Used it as:

```
import Datepicker from 'vue-bulma-datepicker';

export default {
  name: "Clients-new",

  components: {
    VLayout: require('layouts/default/default.vue'),
    Datepicker,
  },
}; 
```
Uncaught SyntaxError: Unexpected token export
    at Object.<anonymous> (app.js:1374)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:1068), <anonymous>:23:24)
    at Object.<anonymous> (app.js:1068)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:1416), <anonymous>:7:3)
    at Object.<anonymous> (app.js:1416)
    at __webpack_require__ (app.js:556)
(anonymous) @ app.js:1374
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ index.vue?52ce:11
(anonymous) @ app.js:1068
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ index.vue?e15a:7
(anonymous) @ app.js:1416
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ new.js?afa7:7
(anonymous) @ app.js:1104
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ new.vue?03a4:3
(anonymous) @ app.js:1398
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ routes.js?38fb:32
(anonymous) @ app.js:936
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ bootstrap.js?901c:84
(anonymous) @ app.js:744
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ index.vue?6dc0:18
(anonymous) @ app.js:1080
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ index.vue?0af8:3
(anonymous) @ app.js:1386
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ main.js?3479:8
(anonymous) @ app.js:1050
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ app.js:587
__webpack_require__ @ app.js:556
(anonymous) @ app.js:579
(anonymous) @ app.js:582
backend.js:1 

webpack:///./~/vue-click-outside/index.js?5eb1

**Comment by luventa** [comment]
what's your webpack version?

**Comment by vniko** [comment]
1.13.2

**Comment by luventa** [comment]
you need to upgrade webpack to 2.x to support native js.

**Comment by vniko** [comment]
Thanks,
Would be great if    you mention it somewheere  in requirements

**Comment by luventa** [comment]
Yes. I will add `peerDependencies` or documents for it.
Thank you very much!
