### ISSUE TITLE
TypeError: hooks[i] is not a function

### ISSUE THREAD

**Issue by MBach** [vue-bulma/datepicker#24]
Hi,
I've launched latest https://github.com/vue-bulma/vue-admin and there is a problem with the datepicker component.
In the console (in watch function), I never have a single valid value displayed, but every time I have:

    TypeError: e.composedPath is not a function
    TypeError: hooks[i] is not a function

Any idea why?

**Comment by dbalas** [comment]
I solved this setting onChange event in config object
`
this.config.onChange = (d, s) => {
    console.log("onChange")
    this.date = s;
}
`

**Comment by luventa** [comment]
It's a compatibility issue. I'm trying to fix it.

**Comment by luventa** [comment]
reopen whenever you want. Thanks.

**Comment by MBach** [comment]
It's working fine. Great job!
