### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by EmilMoe** [vue-bulma/datepicker#3]
When I try to parse it with browserify I get this error:

``` shell
[20:57:51] Starting 'browserify'...
{ Error: Parsing file /home/emil/node_modules/vue-bulma-datepicker/src/Datepicker.vue: Unexpected token (1:0)
```

I import it using 

``` javascript
import Datepicker         from 'vue-bulma-datepicker';
```

**Comment by sanbeaman** [comment]
any word on this? I'm getting the same issue.

`Browserify Failed!: Parsing file ......... /node_modules/vue-bulma-datepicker/src/Datepicker.vue: Unexpected token (1:0)`

**Comment by EmilMoe** [comment]
@sanbeaman take a look here, I made it work:

https://laracasts.com/discuss/channels/vue/flatpickr

**Comment by sanbeaman** [comment]
so it looks like you abandoned the vue-bulma-datepicker and rolled your own with flatpickr directly..

**Comment by EmilMoe** [comment]
Yeah.. I was struggling making it work and was under presssure.

**Comment by sanbeaman** [comment]
thanks, I'll try and do the same!

**Comment by fundon** [comment]
@EmilMoe  Could you post a PR?

**Comment by CMLL** [comment]
I ran into this same problem, and found out that transforming the file with vueify makes the error go away,

`browserify -t vueify -e src/main.js -o web/app.js`

but unfortunately for me, that also other stuff on my application, so if anyone finds what to make to avoid having to vueify the component would be great.
