### ISSUE TITLE
Datepicker closes when selecting one of year / month / hour / minute

### ISSUE THREAD

**Issue by andreapavoni** [vue-bulma/datepicker#31]
When datepicker is open, if I select a day it stills remains open. However, when I change one of year/month/hour/minute it sets the value on input but it also closes the datepicker. This means that I want to set hour from 12 to 14 it closes when I click on the arrow-up to increase the hour.

does anyone have the same issue?

**Comment by andreapavoni** [comment]
Just some more details on this issue: I've found that the directive `ClickOutside` in `index.vue` is responsible for this behaviour. It looks like that it considers clicks outside the _days grid_ as something not related to the datepicker.

**Comment by andreapavoni** [comment]
Entirely removing the `vue-click-outside` directive solves the problem

**Comment by kennonb** [comment]
I see this same behavior in Firefox 53 or later. Doesn't seem to happen in Chrome or Safari. Not sure if that's helpful or not.

**Comment by luventa** [comment]
I made some change for this component. It not uses `vue-click-outside` anymore. This issue shall be fixed.
