### ISSUE TITLE
Error in callback for watcher "config"

### ISSUE THREAD

**Issue by freimaks** [vue-bulma/datepicker#43]
An error occurs when updating the page content:

```
[Vue warn]: Error in callback for watcher "config": 
(found in <Datepicker> at mydisk:\myproject\node_modules\vue-bulma-datepicker\src\index.vue
```

![image 6](https://cloud.githubusercontent.com/assets/26241659/25774526/2dbe7698-3299-11e7-8d09-98567b926358.png)

**Comment by beliolfa** [comment]
It is caused by an error in index.vue.

There are two `methods` declarations, the last one overrides the first one.

**Comment by peteleco** [comment]
There's two PR's [#38](https://github.com/vue-bulma/datepicker/pull/38) [#39](https://github.com/vue-bulma/datepicker/pull/39)  fixing this

**Comment by KKSzymanowski** [comment]
Until @luventa merges the fix, it should work on v. 1.3.0 from March 6th.

**Comment by rcubitto** [comment]
Is it possible to merge either of these PRs? It's a quick fix and it's affecting everyone.

**Comment by moonlik** [comment]
@fundon @luventa please merge these PRs!

**Comment by AlbertClo** [comment]
I have this problem too. I can confirm that the pull request solves the problem as well. Merge please :)

**Comment by FroeMic** [comment]
Yeah, please merge one of these PRs 💃

**Comment by KKSzymanowski** [comment]
@fundon @luventa I understand it's open source, you're doing it for free and I'm in no position to demand active participation, but please just hit the damn Merge button.

**Comment by luventa** [comment]
Yes sir, pr has been merged and new version is just published. 😢
