### ISSUE TITLE
UglifyJs Unexpected token: punc ()

### ISSUE THREAD

**Issue by chimit** [vue-bulma/datepicker#45]
I can't build the project with [WebPack](https://github.com/vuejs-templates/webpack). When I run `npm run build` I get:
```
ERROR in static/js/vendor.f5f763bc19f974345e9c.js from UglifyJs
Unexpected token: punc ()) [./~/vue-bulma-datepicker/src/BaseInput.js:6,0][static/js/vendor.f5f763bc19f974345e9c.js:5283,16]
```

**Comment by angganegara** [comment]
I had this problem and after a very frustrating google search, it seems you need to install Babel preset with shorthand-properties plugins.

**Comment by Van-Vu** [comment]
@angganegara could you elaborate please? I'm also facing the same issue

**Comment by angganegara** [comment]
@Van-Vu have you update the script to the latest version? it seems the error is no longer present.

you can also try changing the source file directly. look for this code : `default: () => ({})` and replace it with : `default: function() { return {} }`

**Comment by Van-Vu** [comment]
@angganegara Yeah, I've just updated the latest babels and it works
Sorry I should have done that before asking
Thanks a lot !

**Comment by larsjanssen6** [comment]
@Van-Vu sorry pretty new to all of this. How can I fix this? I use Laravel mix. I just ran npm update and so it has the newest version. Still receive that error ^?

Thanks  a lot!

**Comment by angganegara** [comment]
@larsjanssen6 I only know the workaround for this. Open the file in node_modules/vue-bulma-datepicker/src/BasicInput.js and look for this code : `default: () => ({})` and replace it with : `default: function() { return {} }`

**Comment by larsjanssen6** [comment]
@angganegara thanks that works. Wondering now why this is not being changed within this package?

**Comment by larsjanssen6** [comment]
@angganegara I already see there is a pull request for this sorry.

**Comment by CryDeTaan** [comment]
I am still getting this error even though I can see that BasicInput.js has been updated after npm update.
Any ideas?

**Comment by havgry** [comment]
@CryDeTaan Yep, a new release including https://github.com/vue-bulma/datepicker/commit/bf7e6d48589b7c3952e395c3cea70260491a5ebf is still pending.

**Comment by CryDeTaan** [comment]
Perfect thanks, Implemented #67 manually in the meantime.

**Comment by lpulatie** [comment]
@fundon 
Any idea on when the new release will be?

**Comment by KKSzymanowski** [comment]
Before it's released you can pull the latest version by specifying the GitHub repository and the commit hash:
```js
"dependencies": {
    "vue-bulma-datepicker": "git://github.com/vue-bulma/datepicker#bf7e6d4"
}
```

**Comment by lpulatie** [comment]
Thanks. That’s what I ended up doing.


On August 28, 2017 at 9:36:29 AM, Kuba Szymanowski (notifications@github.com)
wrote:

Before it's released you can pull the latest version by specifying the
GitHub repository and the commit hash:

"dependencies": {
    "vue-bulma-datepicker": "git://github.com/vue-bulma/datepicker#bf7e6d4"
}

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/vue-bulma/datepicker/issues/45#issuecomment-325371567>,
or mute the thread

**Comment by janva255** [comment]
Can you please push a new release?

**Comment by JeremieLapert** [comment]
Can you please push a new release?

**Comment by angganegara** [comment]
just use this instead https://github.com/ankurk91/vue-flatpickr-component since the owner of this package doesn't seem to update anymore. I already did.

**Comment by JeremieLapert** [comment]
It"s done, it works ! 

thank you !
