### ISSUE TITLE
v-model issue

### ISSUE THREAD

**Issue by sebpl007** [vue-bulma/datepicker#5]
I am having the issue with v-model because when I apply new v-model variable it, the component doesn't pass the data to it and I have noticed that the field already has v-model variable which is "value" but when I try top print out this data and selecting new date it doesn't work... How should I do this part?

**Comment by marcpaskell** [comment]
I think this is because the change isnt emitted... it should have something like this in place so you can use the v-model

in index.vue

  mounted () {
    if (!this.datepicker) {
      this.datepicker = new Datepicker(this.$el, this.config, this.l10n)
      this.datepicker.set('onChange', (d, s) => {
        this.value = s
        **this.$emit('input', s)**
      })
    }
  }

**Comment by victorkurauchi** [comment]
i was facing a similar issue, so what @squalli2008 helped.

mycomponent.js

```
<datepicker
   @update="handleDateStartChange"
    :config="{ minDate: today, wrap: true, dateFormat: 'd/m/Y' }">
 </datepicker>
```

vue-bulma-datepicker/index.vue

```
mounted () {
  if (!this.datepicker) {
    this.datepicker = new Datepicker(this.$el, this.config, this.l10n)
    this.datepicker.set('onChange', (d, s) => {
      this.value = s
      this.$emit('update', d) // new line
    })
  }
}
```

**Comment by vetalball** [comment]
@squalli2008 I have the same problem, but your solution doesn't work for me.
When I add:
```
mounted () {
  if (!this.datepicker) {
    this.datepicker = new Datepicker(this.$el, this.config, this.l10n)
    this.datepicker.set('onChange', (d, s) => {
      this.value = s
      this.$emit('update', d) // new line
    })
  }
}
```

I get an error:
```
TypeError: __WEBPACK_IMPORTED_MODULE_4_vue_bulma_datepicker___default.a is not a constructor
```
Do you have any idea how it can be fixed?

**Comment by romines** [comment]
Wait, what is the point of a datepicker if you can't the value out? Can you not use v-model with any Vue Bulma components?

**Comment by vetalball** [comment]
The issue is fixed, can be closed.
