### ISSUE TITLE
Selecting another month will cause the object to remain being focused

### ISSUE THREAD

**Issue by jarkyll** [vue-bulma/datepicker#50]
```
Uncaught TypeError: Cannot read property 'focus' of undefined
    at Array.eval (eval at <anonymous> (:8080/app.js:5257), <anonymous>:1318:32)
    at processPostDayAnimation (eval at <anonymous> (:8080/app.js:5257), <anonymous>:286:26)
    at HTMLDivElement.animateDays (eval at <anonymous> (:8080/app.js:5257), <anonymous>:310:6)
```
- If you select a date that it not in the current month shown on the date picker, the input tag will still remain focused and the above error will be shown in the console. 
- For example, if you have the month of July shown in the datepicker and you select a date that is shown in the datepicker aka (August 1st), the datepicker will remain focused and the error above will be shown in the console.

![screen shot 2017-06-02 at 12 56 35 pm](https://cloud.githubusercontent.com/assets/5729070/26738236/f923dff4-4792-11e7-96a2-30661c7c8d69.png)

**Comment by luventa** [comment]
Sorry but I cannot repo this error.
Can you try this [demo](https://github.com/luventa/datepicker-demo) or provide your code please?
