### ISSUE TITLE
syntax error on BasicInput when running tests

### ISSUE THREAD

**Issue by EstebanMDQ** [vue-bulma/datepicker#52]
I'm using vue-bulma-datepicker on a project and I'm  getting this error when running unit tests

        PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
          SyntaxError: Unexpected token ')'
          at webpack:///~/vue-bulma-datepicker/src/BasicInput.js:9:0 <- index.js:8795

the only way I managed to fix it is by changing the following on BasicInput.js

```
    inputClass: {
      type: Object,
      // default: () => ({})
      default: function () {
        return {}
      }
    },
```

I'm not sure if this is an error on the package or some miss-configuration on my babel settings.

**Comment by EstebanMDQ** [comment]
after I open this issue I realised that this is related to #27 . the solution proposed there avoids this issue. 
so I'm closing this one.

**Comment by luventa** [comment]
thanks.
