### ISSUE TITLE
Warn Custom Element 

### ISSUE THREAD

**Issue by recs182** [vue-bulma/datepicker#7]
I trying to use this datepicker in my project but I'm getting this issue:
```
[Vue warn]: Unknown custom element: <partial> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in component <datepicker> at E:\_dev\lolch\node_modules\vue-bulma-datepicker\src\Datepicker.vue)
```

I imported it and also registered in components object as you can see bellow:
`import Datepicker from 'vue-bulma-datepicker';`
```
components: {
		Datepicker,
...
```

And I have it in my template
`<datepicker :config="{ dateFormat: 'd-m-Y' }" value="person.born"></datepicker>`

Any suggestion?

**Comment by fundon** [comment]
Thanks. Please try v1.2.1.
